name: deploy to lambda
on:
  push:
    branches: [ main ]

jobs:
  deploy_source:
    name: build and deploy lambda
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Npm Install
        run: |
          npm ci --production
      - name: zip
        uses: montudor/action-zip@v0.1.1
        with:
          args: zip -qq -r ./bundle.zip ./
      - name: default deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_LAMBDA }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_LAMBDA }}
          aws_region: us-east-1
          function_name: phcode-extensions-dev
          zip_file: bundle.zip